# Generated by Django 3.1.1 on 2020-09-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_type',
            field=models.IntegerField(default=0),
        ),
    ]
